{
 "title": "ELB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "listRegions()" },
   {
    "name": "lbaas_instance_id",
    "label": "Elastic Load Balancer",
    "query": "listDims($region,SYS.ELB,lbaas_instance_id,lbaas_instance_id)"
   },
   {
    "name": "lbaas_listener_id",
    "label": "Listener",
    "query": "listDims($region,SYS.ELB,$lbaas_instance_id;lbaas_listener_id,lbaas_listener_id)"
   },
   {
    "name": "lbaas_pool_id",
    "label": "Backend Server Groups",
    "query": "listDims($region,SYS.ELB,$lbaas_instance_id;lbaas_pool_id,lbaas_pool_id)"
   },
   { "name": "filter", "label": "Fiter", "query": "listFilterOptions()" },
   { "name": "period", "label": "Period", "query": "listPeriodOptions()" }
  ]
 },
 "panels": [
  { "title": "Elastic load balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "healthy servers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "ma_normal_servers",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "unhealthy servers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m9_abnormal_servers",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "inbound rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m7_in_Bps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m2_act_conn",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "inactive connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m3_inact_conn",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "new connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m4_ncps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "incoming packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m5_in_pps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "outgoing packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m6_out_pps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "inbound rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m7_in_Bps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "concurrent connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_listener_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m1_cps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_listener_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m2_act_conn",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "inactive connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_listener_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m3_inact_conn",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "new connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_listener_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m4_ncps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "incoming packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_listener_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m5_in_pps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "outgoing packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_listener_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m6_out_pps",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "Backend Server Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "healthy servers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_pool_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "ma_normal_servers",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "unhealthy servers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "dimstr": "lbaas_instance_id:00000000-0000-0000-0000-000000000000,lbaas_pool_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "m9_abnormal_servers",
     "namespace": "SYS.ELB",
     "period": "1",
     "region": "-"
    }
   ]
  }
 ]
}