{
 "title": "RDS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "listRegions()" },
   {
    "name": "rds_cluster_id",
    "label": "MySQL",
    "query": "listDims($region,SYS.RDS,rds_cluster_id,rds_cluster_id)"
   },
   {
    "name": "gaussdb_instance_id",
    "label": "GaussDB",
    "query": "listDims($region,SYS.RDS,gaussdb_instance_id,gaussdb_instance_id)"
   },
   {
    "name": "rds_cluster_sqlserver_id",
    "label": "SqlServer",
    "query": "listDims($region,SYS.RDS,rds_cluster_sqlserver_id,rds_cluster_sqlserver_id)"
   },
   {
    "name": "postgresql_cluster_id",
    "label": "PostgreSql",
    "query": "listDims($region,SYS.RDS,postgresql_cluster_id,postgresql_cluster_id)"
   },
   { "name": "filter", "label": "Fiter", "query": "listFilterOptions()" },
   { "name": "period", "label": "Period", "query": "listPeriodOptions()" }
  ]
 },
 "panels": [
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "rds_cluster_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rds001_cpu_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "rds_cluster_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rds002_mem_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "rds_cluster_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rds003_iops",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "GaussDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "gaussdb_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rds001_cpu_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "gaussdb_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rds002_mem_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "gaussdb_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rds003_iops",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "SQL Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "rds_cluster_sqlserver_id:000000000000000000000000000000000000",
     "filter": "average",
     "metricName": "rds001_cpu_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "rds_cluster_sqlserver_id:000000000000000000000000000000000000",
     "filter": "average",
     "metricName": "rds002_mem_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "rds_cluster_sqlserver_id:000000000000000000000000000000000000",
     "filter": "average",
     "metricName": "rds003_iops",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "PostgreSql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "postgresql_cluster_id:000000000000000000000000000000000000",
     "filter": "average",
     "metricName": "rds001_cpu_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "postgresql_cluster_id:000000000000000000000000000000000000",
     "filter": "average",
     "metricName": "rds002_mem_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "postgresql_cluster_id:000000000000000000000000000000000000",
     "filter": "average",
     "metricName": "rds003_iops",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "-"
    }
   ]
  }
 ]
}